Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/c/Users/Alaa/git/AutoFE_EA/Evaluation/evaluation_trajectory.py", line 97, in <module>
    new_x_train, new_x_test = apply_trajectory_simultaneuosly(X_train, X_test, trajectory[i],opr_names,test_scores)
ValueError: too many values to unpack (expected 2)